GPT2_VARIANT: "bark_coarse"
batch_size: 1
kv_engine_path: ./models/bark_coarse/trt-engine/bark_coarse-kv_cache_bs1.engine
use_cache: True
fp16: True
model:
  bias: False
  block_size: 1024
  dropout: 0.0
  input_vocab_size: 12096
  n_embd: 768
  n_head: 12
  n_layer: 12
  output_vocab_size: 12096
  use_cache: True
  vocab_size: 2096
