apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tts
  template:
    metadata:
      labels:
        app: tts
    spec:
      containers:
        - name: tts
          image: gcr.io/air-pulumi/tts:1.1.test.1225 # Use the appropriate tag/version
          resources:
            limits:
              nvidia.com/gpu: 1 # Request one GPU
          ports:
            - containerPort: 5000 # Replace with the port your server uses
          readinessProbe:
            httpGet:
              port: 5000
              path: /process_available
            periodSeconds: 10
            failureThreshold: 1
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              port: 5000
              path: /is_alive
            periodSeconds: 20
            failureThreshold: 2
            initialDelaySeconds: 100
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-l4"
