apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tts-rule
spec:
  host: tts-service
  trafficPolicy:
    loadBalancer:
#      consistentHash:
#        httpHeaderName: CallID
#        ringHash:
#          minimumRingSize: 10

      simple: LEAST_REQUEST