apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: istio
  rules:
    - http:
        paths:
        - path: "/CA123/synthesize"
          pathType: Prefix
          backend:
            service:
              name: tts-service
              port:
                number: 5000
